version: '3'

services:
  tests:
    build: .
    container_name: p4tc_tests
    devices:
      - "/dev/kvm"
    env_file:
      - .env
    entrypoint:
    - /bin/bash
    - -c
    - "/home/iproute2/configure && make -C /home/iproute2 -j $$(nproc) && make -C /home/iproute2 install && /home/linux/tools/testing/selftests/tc-testing/vm.sh ${ARCH} ${ROOT} ${CPU} ${MEMORY} ${JOBS} ${IMAGE} ${CONFIG} ${DRY} ${CONFIG_GEN} ${SCRIPT}"
    volumes:
      - ${LINUX_PATH}:/home/linux
      - ${IPROUTE2_PATH}:/home/iproute2

  shell:
    build: .
    container_name: p4tc_shell
    profiles: ["shell"]
    devices:
      - "/dev/kvm"
    env_file:
      - .env
    entrypoint:
    - /bin/bash
    - -c
    - "/home/iproute2/configure && make -C /home/iproute2 -j $$(nproc) && make -C /home/iproute2 install && /home/linux/tools/testing/selftests/tc-testing/vm.sh ${ARCH} ${ROOT} ${CPU} ${MEMORY} ${JOBS} ${IMAGE} ${CONFIG} -s"
    stdin_open: true
    tty: true 
    volumes:
      - ${LINUX_PATH}:/home/linux
      - ${IPROUTE2_PATH}:/home/iproute2

  
